name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fonte
        uses: actions/checkout@v4

      - name: Instalar Java 21
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Buildar projeto com Maven
        run: mvn clean install
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Start application with Docker Compose
        run: docker-compose up -d

      - name: Aguardar serviço subir
        run: sleep 30  # Aguarda a aplicação ficar pronta (ajuste se necessário)

      - name: Rodar testes automatizados
        run: mvn test
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
